name: Build Teams Filter APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
            libffi-dev libssl-dev libsqlite3-dev libbz2-dev \
            libreadline-dev build-essential git wget
      
      - name: Set up Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p ~/android-sdk/cmdline-tools
          
          # Download and extract command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          
          # Set environment variables
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          
          # Accept licenses and install components
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-36"
          
          # Add build-tools to PATH
          echo "PATH=$HOME/android-sdk/build-tools/36.0.0:$PATH" >> $GITHUB_ENV
      
      - name: Verify Android tools installation
        run: |
          echo "Installed Android tools:"
          ls -la $ANDROID_SDK_ROOT/build-tools/36.0.0/aidl
          which aidl
          aidl --version
      
      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade cython virtualenv buildozer
      
      - name: Build APK
        run: |
          buildozer android debug
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: teamsfilter-apk
          path: bin/*.apk
