name: Build Teams Filter APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.18
      
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
            libffi-dev libssl-dev libsqlite3-dev libbz2-dev \
            libreadline-dev build-essential git wget
      
      - name: Set up Android SDK
        run: |
          mkdir -p ~/android-sdk/cmdline-tools
wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
unzip cmdline-tools.zip -d ~/android-sdk/cmdline-tools
          mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-36"
      
      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade cython virtualenv buildozer
      
      - name: Build APK
        run: |
          buildozer android debug
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: teamsfilter-apk
          path: bin/*.apk
